//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminVehiculos.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Nullable<int> UsuarioId { get; set; }
        public string Codigo { get; set; }
        public string Password { get; set; }
        public string Rol { get; set; }
    }
}
