//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminVehiculos.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public int VehiculoId { get; set; }
        public string Placa { get; set; }
        public Nullable<int> kilometraje { get; set; }
        public Nullable<int> MarcaId { get; set; }
        public Nullable<int> ConductorId { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual Marca Marca { get; set; }
    }
}
